FROM python:3.11-slim

WORKDIR /app

# Copiar dependencias
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiar código de la app
COPY app/ app/

# Exponer puerto interno
EXPOSE 8000

# Arrancar FastAPI apuntando a servidor.py
CMD ["uvicorn", "app.servidor:app", "--host", "0.0.0.0", "--port", "8000"]
